/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddPlayerRouteImport } from './routes/add-player'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveIdRouteImport } from './routes/live.$id'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageIdRouteImport } from './routes/manage.$id'
import { Route as RegisterIdRouteImport } from './routes/register.$id'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsNewRouteImport } from './routes/tournaments.new'
import { Route as TournamentIdHistoryRouteImport } from './routes/tournament.$id.history'
import { Route as TournamentIdResultsRouteImport } from './routes/tournament.$id.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlayerRoute = AddPlayerRouteImport.update({
  id: '/add-player',
  path: '/add-player',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIdRoute = LiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIdRoute = ManageIdRouteImport.update({
  id: '/manage/$id',
  path: '/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIdRoute = RegisterIdRouteImport.update({
  id: '/register/$id',
  path: '/register/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsNewRoute = TournamentsNewRouteImport.update({
  id: '/tournaments/new',
  path: '/tournaments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIdHistoryRoute = TournamentIdHistoryRouteImport.update({
  id: '/tournament/$id/history',
  path: '/tournament/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIdResultsRoute = TournamentIdResultsRouteImport.update({
  id: '/tournament/$id/results',
  path: '/tournament/$id/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-player': typeof AddPlayerRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/live/$id': typeof LiveIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/register/$id': typeof RegisterIdRoute
  '/team/$id': typeof TeamIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/live/': typeof LiveIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournament/$id/history': typeof TournamentIdHistoryRoute
  '/tournament/$id/results': typeof TournamentIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-player': typeof AddPlayerRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/live/$id': typeof LiveIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/register/$id': typeof RegisterIdRoute
  '/team/$id': typeof TeamIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/live': typeof LiveIndexRoute
  '/manage': typeof ManageIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournament/$id/history': typeof TournamentIdHistoryRoute
  '/tournament/$id/results': typeof TournamentIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-player': typeof AddPlayerRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/live/$id': typeof LiveIdRoute
  '/manage/$id': typeof ManageIdRoute
  '/register/$id': typeof RegisterIdRoute
  '/team/$id': typeof TeamIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/live/': typeof LiveIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournament/$id/history': typeof TournamentIdHistoryRoute
  '/tournament/$id/results': typeof TournamentIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-player'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/profile'
    | '/live/$id'
    | '/manage/$id'
    | '/register/$id'
    | '/team/$id'
    | '/tournaments/new'
    | '/live/'
    | '/manage/'
    | '/tournaments/'
    | '/tournament/$id/history'
    | '/tournament/$id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-player'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/profile'
    | '/live/$id'
    | '/manage/$id'
    | '/register/$id'
    | '/team/$id'
    | '/tournaments/new'
    | '/live'
    | '/manage'
    | '/tournaments'
    | '/tournament/$id/history'
    | '/tournament/$id/results'
  id:
    | '__root__'
    | '/'
    | '/add-player'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/profile'
    | '/live/$id'
    | '/manage/$id'
    | '/register/$id'
    | '/team/$id'
    | '/tournaments/new'
    | '/live/'
    | '/manage/'
    | '/tournaments/'
    | '/tournament/$id/history'
    | '/tournament/$id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPlayerRoute: typeof AddPlayerRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ProfileRoute: typeof ProfileRoute
  LiveIdRoute: typeof LiveIdRoute
  ManageIdRoute: typeof ManageIdRoute
  RegisterIdRoute: typeof RegisterIdRoute
  TeamIdRoute: typeof TeamIdRoute
  TournamentsNewRoute: typeof TournamentsNewRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ManageIndexRoute: typeof ManageIndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  TournamentIdHistoryRoute: typeof TournamentIdHistoryRoute
  TournamentIdResultsRoute: typeof TournamentIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-player': {
      id: '/add-player'
      path: '/add-player'
      fullPath: '/add-player'
      preLoaderRoute: typeof AddPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$id': {
      id: '/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof LiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$id': {
      id: '/manage/$id'
      path: '/manage/$id'
      fullPath: '/manage/$id'
      preLoaderRoute: typeof ManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$id': {
      id: '/register/$id'
      path: '/register/$id'
      fullPath: '/register/$id'
      preLoaderRoute: typeof RegisterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/new': {
      id: '/tournaments/new'
      path: '/tournaments/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof TournamentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$id/history': {
      id: '/tournament/$id/history'
      path: '/tournament/$id/history'
      fullPath: '/tournament/$id/history'
      preLoaderRoute: typeof TournamentIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$id/results': {
      id: '/tournament/$id/results'
      path: '/tournament/$id/results'
      fullPath: '/tournament/$id/results'
      preLoaderRoute: typeof TournamentIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPlayerRoute: AddPlayerRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ProfileRoute: ProfileRoute,
  LiveIdRoute: LiveIdRoute,
  ManageIdRoute: ManageIdRoute,
  RegisterIdRoute: RegisterIdRoute,
  TeamIdRoute: TeamIdRoute,
  TournamentsNewRoute: TournamentsNewRoute,
  LiveIndexRoute: LiveIndexRoute,
  ManageIndexRoute: ManageIndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  TournamentIdHistoryRoute: TournamentIdHistoryRoute,
  TournamentIdResultsRoute: TournamentIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
